# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hugo Minimal Theme"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "A base minimal theme for Hugo framework"
copyright = "© 2020 <a href='https://github.com/wes-o/hugo-minimal-theme'>Hugo Minimal Theme</a>. Made by <a href='https://github.com/wes-o'>@wes-o</a>."
homepage = "https://github.com/wes-o/hugo-minimal-theme"
tags = ["minimal"]
features = ["blog", "emoji", "responsive"]
min_version = "0.41.0"

[author]
  name = "Wes Oler"
  homepage = "https://github.com/wes-o"

# If porting an existing theme
[original]
  name = "hugo-minimal-theme"
  homepage = "https://github.com/wes-o/hugo-minimal-theme"
  repo = "https://github.com/wes-o/hugo-minimal-theme.git"
